// ==========================================================
// MATRIZ TI - Diagrama Entidad-Relación Final
// ==========================================================

Table roles {
  id_rol integer [pk, increment]
  nombre_rol varchar
  descripcion varchar
}

Table usuarios {
  id_usuario integer [pk, increment]
  nombre varchar
  apellido varchar
  correo varchar [unique]
  password_hash varchar
  activo boolean
  id_rol integer [ref: > roles.id_rol]
}

Table empleados {
  id_empleado integer [pk, increment]
  nombre varchar
  apellido varchar
  area varchar
}

Table permisos {
  id_permiso integer [pk, increment]
  id_usuario integer [ref: > usuarios.id_usuario]
  lectura boolean
  escritura boolean
  modificacion boolean
}

Table activos {
  id_activo integer [pk, increment]
  numero_serie varchar [unique]
  marca varchar
  modelo varchar
  tipo_activo varchar
  estado varchar
  id_empleado integer [ref: > empleados.id_empleado]
  id_usuario_registro integer [ref: > usuarios.id_usuario]
  fecha_registro timestamp
}

Table historial_activos {
  id_historial integer [pk, increment]
  id_activo integer [ref: > activos.id_activo]
  id_usuario integer [ref: > usuarios.id_usuario]
  accion varchar
  fecha timestamp
}